"""added username

Revision ID: 68813c6d7baa
Revises: 8054c1887eb2
Create Date: 2021-10-09 23:24:34.760164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68813c6d7baa'
down_revision = '8054c1887eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
